### ISSUE TITLE
Minor Bugfixes / Suggestions for the README

### ISSUE THREAD

**Issue by shyamupa** [strubell/preprocess-conll05#4]
Thanks for setting this up, really makes life easier for preprocessing. 
 
It might be useful to say that the wsj path points to the mrg part of the parsed corpus in PTB, something like
```bash
WSJ=.../LDC99T42/treebank_3/parsed/mrg/wsj/
```
There are other options like `parsed/prd/wsj`, which do not work with the script provided. 

The below exports in file `./bin/basic/get_data.sh` do not have a effect once the script terminates, 
they should be done outside, like the WSJ and BROWN exports, so that other scripts still see these variables.
```bash
export SRLCONLL="`pwd`/srlconll-1.1"
export CONLL05="`pwd`/conll05st-release"
export PERL5LIB=$SRLCONLL/lib:$PERL5LIB
```

Also, where should I get the brown corpus from? I used the one that comes with NLTK, but that does not contain some files (see error below)
```
cat: .../corpora/brown/CK/CK01.MRG: No such file or directory
cat: .../corpora/brown/CK/CK02.MRG: No such file or directory
cat: .../corpora/brown/CK/CK03.MRG: No such file or directory
```

Thanks for the help!

**Comment by pranoy-k** [comment]
Hi Shyamupa,

There is brown corpus which come along with the Penn Tree Bank called test.brown, use that instead of the one from NLTK.
